- name: payment servie configuration
  become: yes
  hosts: payment
  tasks:
  - name: install python3 packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: present
    loop:
    - python3
    - gcc
    - python3-devel

  - name: creating the directory
    ansible.builtin.file:
      name: app
      state: directory

  - name: creating system user
    ansible.builtin.user:
      name: roboshop
      shell:  /sbin/nologin
      system: true
      home: /app

  - name: downloading the service code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip 
      dest: /tmp/payment.zip

  - name: extracting the servie
    ansible.builtin.unarchive:
      src: /tmp/payment.zip
      dest: /app
      remote_src: yes

  - name: installing dependecies
    ansible.builtin.pip:
      requirements: requirements.txt
      executable: pip3.9
    args:
      chdir: /app

  - name: copying payment service
    ansible.builtin.copy:
      src: payment.service
      dest: /etc/systemd/system/payment.service

  - name: Taking daemon-reload
    ansible.builtin.systemd_service:
      daemon_reload: true

  - name: starting and enabling the servie
    ansible.builtin.service:
      name: payment
      state: started
      enabled: yes



  
