- name: configuration of rabbitmq server
  become: yes
  hosts: rabbitmq
  tasks:  
  - name: installing rabbitmq server
    ansible.builtin.dnf:
      name: rabbitmq-server
      state: installed

  - name: starting and enabling servie
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes

  - name: create rabbitmq user
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: roboshop123
      permissions:
        - vhost: /
          configure_priv: .*
          read_priv: .*
          write_priv: .*
      state: present